// <auto-generated />
using System;
using HermesHandling.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HermesHandling.Server.Migrations
{
    [DbContext(typeof(HermesDbContext))]
    partial class HermesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HermesHandling.Server.Models.Compania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("CodigoIcao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("codigo_icao");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pais");

                    b.HasKey("Id")
                        .HasName("PK__compania__3213E83FAC57B8BA");

                    b.HasIndex(new[] { "Nombre" }, "UQ__compania__72AFBCC67DC372DB")
                        .IsUnique();

                    b.HasIndex(new[] { "CodigoIcao" }, "UQ__compania__8F6B95982CF76666")
                        .IsUnique();

                    b.ToTable("companias", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Server.Models.ConfigurationKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PK__Configur__3213E83F1E5DA645");

                    b.HasIndex(new[] { "Clave" }, "UQ__Configur__71DCA3DB5A040AD2")
                        .IsUnique();

                    b.ToTable("ConfigurationKeys");
                });

            modelBuilder.Entity("HermesHandling.Server.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaUltimaRevision")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_ultima_revision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__equipos__3213E83FA945819B");

                    b.ToTable("equipos", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Server.Models.HistorialIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("accion");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime?>("FechaAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_accion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IncidenciaId")
                        .HasColumnType("int")
                        .HasColumnName("incidencia_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__historia__3213E83F294DCF02");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("historial_incidencias", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Server.Models.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AltaId")
                        .HasColumnType("int")
                        .HasColumnName("alta_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("abierta")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int?>("ModificacionId")
                        .HasColumnType("int")
                        .HasColumnName("modificacion_id");

                    b.Property<string>("Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("media")
                        .HasColumnName("prioridad");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("PK__incidenc__3213E83FB5C70A36");

                    b.HasIndex("AltaId");

                    b.HasIndex("ModificacionId");

                    b.ToTable("incidencias", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Server.Models.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int")
                        .HasColumnName("equipo_id");

                    b.Property<DateTime?>("FechaMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_mantenimiento")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TipoMantenimiento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_mantenimiento");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__mantenim__3213E83F25639924");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("mantenimientos", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Server.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<int?>("CompaniaId")
                        .HasColumnType("int")
                        .HasColumnName("compania_id");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contraseña");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("salt");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int")
                        .HasColumnName("tipo_usuario");

                    b.Property<DateTime?>("UltimaSesion")
                        .HasColumnType("datetime")
                        .HasColumnName("ultima_sesion");

                    b.HasKey("Id")
                        .HasName("PK__usuarios__3213E83F398390ED");

                    b.HasIndex("CompaniaId");

                    b.HasIndex(new[] { "Email" }, "UQ__usuarios__AB6E616404D5919E")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Server.Models.HistorialIncidencia", b =>
                {
                    b.HasOne("HermesHandling.Server.Models.Incidencia", "Incidencia")
                        .WithMany("HistorialIncidencia")
                        .HasForeignKey("IncidenciaId")
                        .HasConstraintName("FK__historial__incid__66603565");

                    b.HasOne("HermesHandling.Server.Models.Usuario", "Usuario")
                        .WithMany("HistorialIncidencia")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__historial__usuar__6754599E");

                    b.Navigation("Incidencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HermesHandling.Server.Models.Incidencia", b =>
                {
                    b.HasOne("HermesHandling.Server.Models.Usuario", "Alta")
                        .WithMany("IncidenciaAlta")
                        .HasForeignKey("AltaId")
                        .IsRequired()
                        .HasConstraintName("FK__incidenci__alta___6477ECF3");

                    b.HasOne("HermesHandling.Server.Models.Usuario", "Modificacion")
                        .WithMany("IncidenciaModificacions")
                        .HasForeignKey("ModificacionId")
                        .HasConstraintName("FK__incidenci__modif__656C112C");

                    b.Navigation("Alta");

                    b.Navigation("Modificacion");
                });

            modelBuilder.Entity("HermesHandling.Server.Models.Mantenimiento", b =>
                {
                    b.HasOne("HermesHandling.Server.Models.Equipo", "Equipo")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("EquipoId")
                        .HasConstraintName("FK__mantenimi__equip__68487DD7");

                    b.HasOne("HermesHandling.Server.Models.Usuario", "Usuario")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__mantenimi__usuar__693CA210");

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HermesHandling.Server.Models.Usuario", b =>
                {
                    b.HasOne("HermesHandling.Server.Models.Compania", "Compania")
                        .WithMany("Usuarios")
                        .HasForeignKey("CompaniaId")
                        .HasConstraintName("FK__usuarios__compan__6383C8BA");

                    b.Navigation("Compania");
                });

            modelBuilder.Entity("HermesHandling.Server.Models.Compania", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("HermesHandling.Server.Models.Equipo", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("HermesHandling.Server.Models.Incidencia", b =>
                {
                    b.Navigation("HistorialIncidencia");
                });

            modelBuilder.Entity("HermesHandling.Server.Models.Usuario", b =>
                {
                    b.Navigation("HistorialIncidencia");

                    b.Navigation("IncidenciaAlta");

                    b.Navigation("IncidenciaModificacions");

                    b.Navigation("Mantenimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
