// <auto-generated />
using System;
using HermesHandling.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HermesHandling.Data.Migrations
{
    [DbContext(typeof(HermesDbContext))]
    partial class HermesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HermesHandling.Data.Models.CategoriasEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__categori__3213E83F25E0BF1A");

                    b.ToTable("categorias_equipos", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Comunicacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asunto")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("asunto");

                    b.Property<DateTime?>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_alta")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_publicacion");

                    b.Property<int?>("IdUsuarioAlta")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_alta");

                    b.Property<int?>("IdUsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_modificacion");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.HasKey("Id")
                        .HasName("PK__comunica__3213E83F8A86778A");

                    b.HasIndex("IdUsuarioAlta");

                    b.HasIndex("IdUsuarioModificacion");

                    b.ToTable("comunicaciones", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.ConfigurationKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PK__Configur__3213E83F375EE2AA");

                    b.HasIndex(new[] { "Clave" }, "UQ__Configur__71DCA3DB6D1DCDDA")
                        .IsUnique();

                    b.ToTable("ConfigurationKeys");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.DefectosReportado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ReporteId")
                        .HasColumnType("int")
                        .HasColumnName("reporte_id");

                    b.Property<int?>("TipoDefectoId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_defecto_id");

                    b.HasKey("Id")
                        .HasName("PK__defectos__3213E83F86795D7A");

                    b.HasIndex("ReporteId");

                    b.HasIndex("TipoDefectoId");

                    b.ToTable("defectos_reportados", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.DocumentacionInterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_alta")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int?>("IdUsuarioAlta")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_alta");

                    b.Property<int?>("IdUsuarioModificacion")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_modificacion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("PathDocumento")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("path_documento");

                    b.HasKey("Id")
                        .HasName("PK__document__3213E83F7E489B45");

                    b.HasIndex("IdUsuarioAlta");

                    b.HasIndex("IdUsuarioModificacion");

                    b.ToTable("documentacion_interna", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("asset_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaUltimaRevision")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_ultima_revision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("TipoEquipoId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_equipo_id");

                    b.HasKey("Id")
                        .HasName("PK__equipos__3213E83F93FB54E8");

                    b.HasIndex("TipoEquipoId");

                    b.ToTable("equipos", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.HistorialIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("accion");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime?>("FechaAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_accion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IncidenciaId")
                        .HasColumnType("int")
                        .HasColumnName("incidencia_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__historia__3213E83F27D8813B");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("historial_incidencias", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AltaId")
                        .HasColumnType("int")
                        .HasColumnName("alta_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("abierta")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int?>("ModificacionId")
                        .HasColumnType("int")
                        .HasColumnName("modificacion_id");

                    b.Property<string>("Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("media")
                        .HasColumnName("prioridad");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("PK__incidenc__3213E83F0F5CD9F0");

                    b.HasIndex("AltaId");

                    b.HasIndex("ModificacionId");

                    b.ToTable("incidencias", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int")
                        .HasColumnName("equipo_id");

                    b.Property<DateTime?>("FechaMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_mantenimiento")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TipoMantenimiento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_mantenimiento");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__mantenim__3213E83F389B9D12");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("mantenimientos", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int")
                        .HasColumnName("equipo_id");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ubicacion");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__reportes__3213E83F014DB27C");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("reportes", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.ReportesDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_subida")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("PathDocumento")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("path_documento");

                    b.Property<int?>("ReporteId")
                        .HasColumnType("int")
                        .HasColumnName("reporte_id");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_documento");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__reportes__3213E83F877A5DEA");

                    b.HasIndex("ReporteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("reportes_documentos", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.TiposDefecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__tipos_de__3213E83FB8BB96B0");

                    b.ToTable("tipos_defectos", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.TiposEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaEquipoId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_equipo_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__tipos_eq__3213E83FEA5D86A4");

                    b.HasIndex("CategoriaEquipoId");

                    b.ToTable("tipos_equipos", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("salt");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int")
                        .HasColumnName("tipo_usuario");

                    b.Property<DateTime?>("UltimaSesion")
                        .HasColumnType("datetime")
                        .HasColumnName("ultima_sesion");

                    b.HasKey("Id")
                        .HasName("PK__usuarios__3213E83FA568ADBD");

                    b.HasIndex(new[] { "Email" }, "UQ_usuarios_email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Comunicacione", b =>
                {
                    b.HasOne("HermesHandling.Data.Models.Usuario", "IdUsuarioAltaNavigation")
                        .WithMany("ComunicacioneIdUsuarioAltaNavigations")
                        .HasForeignKey("IdUsuarioAlta")
                        .HasConstraintName("FK__comunicac__id_us__1F98B2C1");

                    b.HasOne("HermesHandling.Data.Models.Usuario", "IdUsuarioModificacionNavigation")
                        .WithMany("ComunicacioneIdUsuarioModificacionNavigations")
                        .HasForeignKey("IdUsuarioModificacion")
                        .HasConstraintName("FK__comunicac__id_us__208CD6FA");

                    b.Navigation("IdUsuarioAltaNavigation");

                    b.Navigation("IdUsuarioModificacionNavigation");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.DefectosReportado", b =>
                {
                    b.HasOne("HermesHandling.Data.Models.Reporte", "Reporte")
                        .WithMany("DefectosReportados")
                        .HasForeignKey("ReporteId")
                        .HasConstraintName("FK__defectos___repor__1BC821DD");

                    b.HasOne("HermesHandling.Data.Models.TiposDefecto", "TipoDefecto")
                        .WithMany("DefectosReportados")
                        .HasForeignKey("TipoDefectoId")
                        .HasConstraintName("FK__defectos___tipo___1CBC4616");

                    b.Navigation("Reporte");

                    b.Navigation("TipoDefecto");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.DocumentacionInterna", b =>
                {
                    b.HasOne("HermesHandling.Data.Models.Usuario", "IdUsuarioAltaNavigation")
                        .WithMany("DocumentacionInternaIdUsuarioAltaNavigations")
                        .HasForeignKey("IdUsuarioAlta")
                        .HasConstraintName("FK__documenta__id_us__2180FB33");

                    b.HasOne("HermesHandling.Data.Models.Usuario", "IdUsuarioModificacionNavigation")
                        .WithMany("DocumentacionInternaIdUsuarioModificacionNavigations")
                        .HasForeignKey("IdUsuarioModificacion")
                        .HasConstraintName("FK__documenta__id_us__22751F6C");

                    b.Navigation("IdUsuarioAltaNavigation");

                    b.Navigation("IdUsuarioModificacionNavigation");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Equipo", b =>
                {
                    b.HasOne("HermesHandling.Data.Models.TiposEquipo", "TipoEquipo")
                        .WithMany("Equipos")
                        .HasForeignKey("TipoEquipoId")
                        .HasConstraintName("FK__equipos__tipo_eq__1332DBDC");

                    b.Navigation("TipoEquipo");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.HistorialIncidencia", b =>
                {
                    b.HasOne("HermesHandling.Data.Models.Incidencia", "Incidencia")
                        .WithMany("HistorialIncidencia")
                        .HasForeignKey("IncidenciaId")
                        .HasConstraintName("FK__historial__incid__17F790F9");

                    b.HasOne("HermesHandling.Data.Models.Usuario", "Usuario")
                        .WithMany("HistorialIncidencia")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__historial__usuar__18EBB532");

                    b.Navigation("Incidencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Incidencia", b =>
                {
                    b.HasOne("HermesHandling.Data.Models.Usuario", "Alta")
                        .WithMany("IncidenciaAlta")
                        .HasForeignKey("AltaId")
                        .HasConstraintName("FK__incidenci__alta___160F4887");

                    b.HasOne("HermesHandling.Data.Models.Usuario", "Modificacion")
                        .WithMany("IncidenciaModificacions")
                        .HasForeignKey("ModificacionId")
                        .HasConstraintName("FK__incidenci__modif__17036CC0");

                    b.Navigation("Alta");

                    b.Navigation("Modificacion");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Mantenimiento", b =>
                {
                    b.HasOne("HermesHandling.Data.Models.Equipo", "Equipo")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("EquipoId")
                        .HasConstraintName("FK__mantenimi__equip__14270015");

                    b.HasOne("HermesHandling.Data.Models.Usuario", "Usuario")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__mantenimi__usuar__151B244E");

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Reporte", b =>
                {
                    b.HasOne("HermesHandling.Data.Models.Equipo", "Equipo")
                        .WithMany("Reportes")
                        .HasForeignKey("EquipoId")
                        .HasConstraintName("FK__reportes__equipo__19DFD96B");

                    b.HasOne("HermesHandling.Data.Models.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__reportes__usuari__1AD3FDA4");

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.ReportesDocumento", b =>
                {
                    b.HasOne("HermesHandling.Data.Models.Reporte", "Reporte")
                        .WithMany("ReportesDocumentos")
                        .HasForeignKey("ReporteId")
                        .HasConstraintName("FK__reportes___repor__1DB06A4F");

                    b.HasOne("HermesHandling.Data.Models.Usuario", "Usuario")
                        .WithMany("ReportesDocumentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__reportes___usuar__1EA48E88");

                    b.Navigation("Reporte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.TiposEquipo", b =>
                {
                    b.HasOne("HermesHandling.Data.Models.CategoriasEquipo", "CategoriaEquipo")
                        .WithMany("TiposEquipos")
                        .HasForeignKey("CategoriaEquipoId")
                        .HasConstraintName("FK__tipos_equ__categ__123EB7A3");

                    b.Navigation("CategoriaEquipo");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.CategoriasEquipo", b =>
                {
                    b.Navigation("TiposEquipos");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Equipo", b =>
                {
                    b.Navigation("Mantenimientos");

                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Incidencia", b =>
                {
                    b.Navigation("HistorialIncidencia");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Reporte", b =>
                {
                    b.Navigation("DefectosReportados");

                    b.Navigation("ReportesDocumentos");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.TiposDefecto", b =>
                {
                    b.Navigation("DefectosReportados");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.TiposEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("HermesHandling.Data.Models.Usuario", b =>
                {
                    b.Navigation("ComunicacioneIdUsuarioAltaNavigations");

                    b.Navigation("ComunicacioneIdUsuarioModificacionNavigations");

                    b.Navigation("DocumentacionInternaIdUsuarioAltaNavigations");

                    b.Navigation("DocumentacionInternaIdUsuarioModificacionNavigations");

                    b.Navigation("HistorialIncidencia");

                    b.Navigation("IncidenciaAlta");

                    b.Navigation("IncidenciaModificacions");

                    b.Navigation("Mantenimientos");

                    b.Navigation("Reportes");

                    b.Navigation("ReportesDocumentos");
                });
#pragma warning restore 612, 618
        }
    }
}
