name: Build and deploy ASP.Net Core + React app to Azure Web App - HermesHandling

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies and build React app
        working-directory: ./HermesHandling/HermesHandling.client
        run: |
          npm ci
          npm run build

      - name: Clean wwwroot
        run: |
          if exist HermesHandling\HermesHandling.server\wwwroot rmdir /s /q HermesHandling\HermesHandling.server\wwwroot

      - name: Copy React build output to server wwwroot
        run: |
          xcopy /E /I /Y HermesHandling\HermesHandling.client\build HermesHandling\HermesHandling.server\wwwroot

      - name: Build with dotnet
        working-directory: ./HermesHandling/HermesHandling.server
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: ./HermesHandling/HermesHandling.server
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_27643B163F03483D9EE601DBE1EAC056 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9740DE80413A42119A770A7FEDAA140A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9FF8D257393645A683AC7268BE39F72B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HermesHandling'
          slot-name: 'Production'
          package: .
